### ISSUE TITLE
anyolite 1,1,0 incompatibility?

### ISSUE THREAD

**Issue by drhuffman12** [Anyolite/ScapoLite#1]
Building the `main.cr` app errors with:

```
$ crystal build main.cr
> INFO: Could not wrap function 'match!' with args [str : String, pos : Int32 = 0, , options : Regex::MatchOptions = :none].
> INFO: Could not wrap function 'Regex.literal' with args [pattern : String, , i : Bool = false, m : Bool = false, x : Bool = false].
```

I had git-clone'd this repo, then ran `shards install` from the cloned copy.

Please help; this concept is so exciting! :)

**Comment by Hadeweka** [comment]
It's a result of recent changes in the Crystal Regex class (the Regex class is wrapped automatically by Anyolite, thus the warnings). I will fix this soon, but it shouldn't cause any other problems besides displaying the warnings.

**Comment by Hadeweka** [comment]
https://github.com/Anyolite/anyolite/commit/cfed3cf6ff51e60725ea36f866d74e8ffb8e4dd8 should remove the warnings.
